### ISSUE TITLE
Right-click events seem to be going to the wrong object.

### ISSUE THREAD

**Issue by shihchengyen** [grero/PanGUI#24]

**Comment by grero** [comment]
I'll try to reproduce this with some dummy data in order to debug it. I have been testing with plotting two objects, and there the click seems to be going to the correct axis.

**Comment by grero** [comment]
It works in-principle with 3 axes.

**Comment by grero** [comment]
Can you try debugging by printing the value of `axidx` in the `onclick` function? This should be near line 96.
